### ISSUE TITLE
Using a new genome

### ISSUE THREAD

**Issue by mullerbsf** [UMCUGenetics/MutationalPatterns#55] opened 2020-10-16 18:57 UTC
Dear,

I am trying to run the MutationalPatterns using Chlamydomonas reinhardtii v5 genome. However, it is not available in the BSgenome library.

I tried to install and load a new genome there. But I had some issues and I was not able to figure out it quickly. Could you please help me with that? How can I load a new genome using the FASTA file? If possible, could you please install it for me? 

The genome (Creinhardtii_281_v5.0.fa) was download from Phytozome: https://phytozome.jgi.doe.gov/pz/portal.html#!info?alias=Org_Creinhardtii

I really appreciate your help!

Best regards,
Barbara.

**Comment by mullerbsf** [comment] 2020-10-20 17:41
Dear @FrancisBlokzijl, 

Could you please help with that?

Thank you!
Barbara.

**Comment by roelj** [comment] 2020-10-20 18:53
Dear @mullerbsf 

I see the issue is not being picked up by the new maintainers.  I think it's best to ask for help at the BSGenome camp, because then you will have the most benefit of having this reference genome uniform across multiple packages. I think [this place](https://support.bioconductor.org/) will help you best.

MutationalPatterns intentionally integrates with BSGenome because they are both part of Bioconductor.

Kind regards,
Roel Janssen

**Comment by mullerbsf** [comment] 2020-10-20 20:39
Dear @roelj 

Thank you for your response. 

I opened an issue on BSgenome (https://github.com/Bioconductor/BSgenome/issues/12). I will be waiting for them to answer me.

Best regards, 
Barbara.

**Comment by roelj** [comment] 2020-10-20 20:47
Thanks @mullerbsf.

Let's leave this issue open for now, so I don't forget to check back later this week to see if you've made progress with BSGenome.

Kind regards,
Roel Janssen

**Comment by hpages** [comment] 2020-11-16 19:12
Hi @roelj ,

Can't MutationalPatterns work directly with a FASTA file? Although your users or the Bioconductor core team could create a BSgenome package for `Creinhardtii_281_v5.0.fa`, it seems like an unnecessary burden to require that MutationalPatterns users have their genome of interest wrapped in a BSgenome package.

Thanks,
H.

**Comment by roelj** [comment] 2020-11-16 20:00
Hi @hpages ,

Thanks for your insight. It can't at the moment.

Wouldn't it be better in general to make use of `BSgenome`?  Then the user has a uniform way across multiple packages to read reference genomes, and since there's only one implementation, the user only needs to have the reference genome in memory once.

The initial burden could be smaller by making it easier to create a `BSgenome` package.

Kind regards,
Roel Janssen

**Comment by mullerbsf** [comment] 2021-01-14 02:49
Dear @roelj

I am trying to run the MutationalPatterns using the genome above as following:

ref_genome <- "BSgenome.Creinhardtii.JGI.v5.6"
library(ref_genome, character.only = TRUE)

vcf_files <- list.files(system.file("extdata", package = "MutationalPatterns"), pattern = SNPGenie.vcf", full.names = TRUE)

sample_names <- c("6-D712-D504","2-D704-D505","3-D705-D505","3-D706-D505","2-D704-D506","3-D705-D506","3-D706-D506","2-D704-D507","3-D705-D507","3-D706-D507","2-D704-D508","3-D705-D508","3-D706-D508")

grl <- read_vcfs_as_granges(vcf_files, sample_names, ref_genome)

However, I got the following error:
Error: Please provide the same number of sample names as VCF files

The VCF file has 13 samples, as described one by one in the “sample_names”. Could you please help me figure out the solution for this error?

Thank you!

Best regards, 
Barbara.

**Comment by roelj** [comment] 2021-01-14 09:15
Hi @mullerbsf,

The function `read_vcfs_as_granges` expects one sample name per VCF file.
Perhaps it's easiest to split your VCF file into multiple VCF files. [Here's a link](https://www.biostars.org/p/130456/#243638) on how to do that.

I don't maintain MutationalPatterns anymore, so for further questions, please ask the new maintainers :).

Kind regards,
Roel Janssen

**Comment by mullerbsf** [comment] 2021-02-02 15:39
Dear @FreekManders or @FrancisBlokzijl

I have a VCF file with a sample test with CRISP output (https://github.com/vibansal/crisp). My data is not regular diploid data as human and other species. My VCF file is for pooled data with ploidy=25:

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  2-D704-D505
1       19404   Chla_rei_1_19404        T       TGC     47552   PASS    AC=147;AF=0.452308;AN=325;CT=-1.7;DP=3584,2492,400;EMstats=4755.27:-2503.09;FLANKSEQ=tgcaccaacg:T:cctgcatccg;HP=0;HWEstats=2.0;MQS=0,0,17,7536;NP=49;NS=13;VF=EMpass;VP=48;VT=INSERTION GT:GQ:DP:AD:RO:AO       0/0/0/0/0/0/0/0/0/0/0/0/0/1/1/1/1/1/1/1/1/1/1/1/1:1:124:70,54:70:54

When I ran your package, I got the same error as before, even using one sample, as @roelj (see above) helped and said that I should split the VCF file by sample:

> vcf_files <- list.files(system.file("extdata", package = "MutationalPatterns"),
+                         pattern = "/test_2-D704-D505.vcf", full.names = TRUE)
> sample_names <- "2-D704-D505"
> grl <- read_vcfs_as_granges(vcf_files, sample_names, ref_genome)
Error: Please provide the same number of sample names as VCF files

Could you please let me know the solution for this issue?
Also, is there an option to run with multiple samples at the same time?

Thank you!

Best regards,
Barbara.

**Comment by FreekManders** [comment] 2021-02-02 16:01
Hi @mullerbsf,

You can run multiple samples at the same time, but each of them should be in a separate vcf. You can then put the filenames of the vcfs in the `vcf_files` variable and the sample names in the `sample_names` variable.

About the error. Is it possible that the `vcf_files` variable now contains more than one filename?
You should provide one sample name per vcf file. You can test this by running:
`length(vcf_files) == length(sample_names)`
This should return `TRUE`

**Comment by mullerbsf** [comment] 2021-02-02 18:19
Dear @FreekManders 

Thank you for your quick response. But the result was false:

>ref_genome <- "BSgenome.Creinhardtii.JGI.v5.6"
>library(ref_genome, character.only = TRUE)

>vcf_files <- list.files(system.file("extdata", package = "MutationalPatterns"), pattern = "test_2-D704-D505.vcf", full.names = TRUE)
>sample_names <- "2-D704-D505"

> length(vcf_files) == length(sample_names)
[1] FALSE

Could it be related to the ploidy of the VCF?

Please I have attached the first 1000 rows of my VCF for your test, as a TXT file.
[test_2-D704-D505.txt](https://github.com/UMCUGenetics/MutationalPatterns/files/5913463/test_2-D704-D505.txt)

Thank you!
Barbara.

**Comment by mullerbsf** [comment] 2021-02-02 21:42
Hi @FreekManders 

I was able to load the VCF file using the following commands. However, I got an error in the glr that does not recognize the BSgenome.Creinhardtii.JGI.v5.6 genome. Could you please assist me with this issue?

> ref_genome <- "BSgenome.Creinhardtii.JGI.v5.6"
> library(ref_genome, character.only = TRUE)
> sample_names <- "2-D704-D505"
> 
> vcf_files <- list.files(pattern = "2-D704-D505.vcf", full.names = TRUE)
> length(vcf_files) == length(sample_names)
[1] TRUE
> grl <- read_vcfs_as_granges(vcf_files, sample_names, ref_genome)
The style does not have a compatible entry for the species supported by Seqname. Please see
  genomeStyles() for supported species/style
Error: The seqlevelStyle of the vcf could not be changed to that of the reference.
                     You can run this function with `change_seqnames = F` and `group = 'all'`, 
                     to prevent this error.
                     However, you then have to make sure that the seqnames (chromosome names) are
                     the same between your vcfs and the reference BSgenome object.
                     (The message of the internal error causing this problem is shown above.)
> grl <- read_vcfs_as_granges(vcf_files, sample_names, ref_genome, change_seqnames = F, group = 'all')
The style does not have a compatible entry for the species supported by Seqname. Please see
  genomeStyles() for supported species/style
Error: The vcf could not be filtered for the specific seqlevels group.
                     You can run this function with `group = 'all'`, to prevent this error.
                     (The message of the internal error causing this problem is shown above.)
> grl <- read_vcfs_as_granges(vcf_files, sample_names, ref_genome, change_seqnames = F, group = "all")
The style does not have a compatible entry for the species supported by Seqname. Please see
  genomeStyles() for supported species/style
Error: The vcf could not be filtered for the specific seqlevels group.
                     You can run this function with `group = 'all'`, to prevent this error.
                     (The message of the internal error causing this problem is shown above.)

**Comment by FreekManders** [comment] 2021-02-03 10:38
There seems to be an issue with the genomeStyle of the BSgenome object. I can't fix that.
Loading the data might work if you try `group = "none"`. That should hopefully circumvent the issue.
Alternatively you could read in a vcf file with `gr <- GenomicRanges::granges(VariantAnnotation::readVcf(vcf_file))`
In both cases, you do have to make sure that the chromosome names in your vcf file match that of the BSgenome object.
The BSgenome object has names like "chromosome_1" (You can see these with `seqnames(BSgenome.Creinhardtii.JGI.v5.6)`) 
Your vcf however has the chromosome name: "1".
Here is a thread with advice on how to change the chromosome names of your vcf: https://www.biostars.org/p/98582/

**Comment by hpages** [comment] 2021-02-04 17:30
Or you could just get rid of the `chromosome_` prefix with:
```
seqnames(BSgenome.Creinhardtii.JGI.v5.6) <- sub("chromosome_", "", seqnames(BSgenome.Creinhardtii.JGI.v5.6))
```

Might be easier than changing the  chromosome names of all your VCF files.

**Comment by mullerbsf** [comment] 2021-02-04 17:56
Dear @FreekManders, @roelj and @hpages

It worked, I am able to run the package. Thank you for all your suggestions and help with these issues.

Best regards,
Barbara.

**Comment by mullerbsf** [comment] 2021-02-04 21:43
Dear @FreekManders and @hpages 

I tried to do the @hpages way to remove the chromosome_ prefix because it would be simple to plot the genomic distribution rainfall plot and because my VCF files were generated without it. However, I am getting an error (see below). I was able to run the MutationalPatterns package editing the VCF file. However, it will make more sense if I can remove the chromosome_ prefix from the original genome to simplify the plots. What do I need to do to solve this?

Thank you!

> # Get rid of the chromosome_ prefix with:
> seqnames(BSgenome.Creinhardtii.JGI.v5.6) <- sub("chromosome_", "", seqnames(BSgenome.Creinhardtii.JGI.v5.6))
> seqnames(BSgenome.Creinhardtii.JGI.v5.6)
 [1] "1"           "2"           "3"           "4"           "5"           "6"          
 [7] "7"           "8"           "9"           "10"          "11"          "12"         
[13] "13"          "14"          "15"          "16"          "17"          "scaffold_18"
[19] "scaffold_19" "scaffold_20" "scaffold_21" "scaffold_22" "scaffold_23" "scaffold_24"
[25] "scaffold_25" "scaffold_26" "scaffold_27" "scaffold_28" "scaffold_29" "scaffold_30"
[31] "scaffold_31" "scaffold_32" "scaffold_33" "scaffold_34" "scaffold_35" "scaffold_36"
[37] "scaffold_37" "scaffold_38" "scaffold_39" "scaffold_40" "scaffold_41" "scaffold_42"
[43] "scaffold_43" "scaffold_44" "scaffold_45" "scaffold_46" "scaffold_47" "scaffold_48"
[49] "scaffold_49" "scaffold_50" "scaffold_51" "scaffold_52" "scaffold_53" "scaffold_54"

> # 96 mutational profile
> mut_mat <- mut_matrix(vcf_list = grl, ref_genome = ref_genome)
Error: The following seqlevels (chromosome names) occur in the input GRanges,but are not present in the ref_genome: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17. An example of how to fix this is show below.
        First select the chromosomes you want to keep with: 
        `chromosomes = paste0('chr', c(1:22,'X'))`
        You can then remove variants in other chromosomes with: 
        `seqlevels(grl, pruning.mode = 'tidy') = chromosomes`

**Comment by hpages** [comment] 2021-02-04 22:40
Can you show us the output of `seqnames(ref_genome)`?

**Comment by mullerbsf** [comment] 2021-02-04 22:53
> seqnames(ref_genome)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"character"’

**Comment by hpages** [comment] 2021-02-04 23:20
ah, so you are not supplying the genome with the modified seqnames here?

Looks like you are supplying _the name_ of the genome (`"BSgenome.Creinhardtii.JGI.v5.6"`). This refers to the original _unmodified_ BSgenome object contained in the **BSgenome.Creinhardtii.JGI.v5.6** package. What you want to supply instead is _the modified BSgenome object_. So you want to do something like this:
```
library(BSgenome.Creinhardtii.JGI.v5.6)
ref_genome <- BSgenome.Creinhardtii.JGI.v5.6
seqnames(ref_genome) <- sub("chromosome_", "", seqnames(ref_genome))
mut_mat <- mut_matrix(vcf_list=grl, ref_genome=ref_genome)
```

**Comment by mullerbsf** [comment] 2021-02-05 01:20
Dear @hpages 

It worked for most of the MutationalPatterns functions. However, I got the following error trying to plot the rainfall plot with the 17 chromosomes:

> seqnames(ref_genome)
 [1] "1"           "2"           "3"           "4"           "5"           "6"          
 [7] "7"           "8"           "9"           "10"          "11"          "12"         
[13] "13"          "14"          "15"          "16"          "17"          "scaffold_18"
[19] "scaffold_19" "scaffold_20" "scaffold_21" "scaffold_22" "scaffold_23" "scaffold_24"
[25] "scaffold_25" "scaffold_26" "scaffold_27" "scaffold_28" "scaffold_29" "scaffold_30"
[31] "scaffold_31" "scaffold_32" "scaffold_33" "scaffold_34" "scaffold_35" "scaffold_36"
[37] "scaffold_37" "scaffold_38" "scaffold_39" "scaffold_40" "scaffold_41" "scaffold_42"
[43] "scaffold_43" "scaffold_44" "scaffold_45" "scaffold_46" "scaffold_47" "scaffold_48"
[49] "scaffold_49" "scaffold_50" "scaffold_51" "scaffold_52" "scaffold_53" "scaffold_54"

> # Define 17 chromosomes
> chromosomes <- seqnames(get(ref_genome))[1:17]
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'seqnames': invalid first argument
> 
> # Make a rainfall plot
> plot_rainfall(grl[[1]],
+               title = names(grl[1]),
+               chromosomes = chromosomes, cex = 1.5, ylim = 1e+09
+ )
Error: Chromosome lengths missing from vcf object.
 Likely cause: contig lengths missing from the header of your vcf file(s).
 Please evaluate: seqinfo(vcf)
 To add seqlengths to your vcf GRanges object use: seqlengths(vcf) <- 

Thank you!

**Comment by mullerbsf** [comment] 2021-02-05 01:24
If I have the "get":

> chromosomes <- seqnames(ref_genome)[1:17]
> plot_rainfall(grl[[1]], title = names(grl[1]), chromosomes = chromosomes, cex = 1.5, ylim = 1e+09)
Error: Chromosome lengths missing from vcf object.
 Likely cause: contig lengths missing from the header of your vcf file(s).
 Please evaluate: seqinfo(vcf)
 To add seqlengths to your vcf GRanges object use: seqlengths(vcf) <-

**Comment by hpages** [comment] 2021-02-05 03:17
IIUC `plot_rainfall()` wants to see the chromosome lengths in the supplied GRanges object (`grl[[1]]`) but it seems that your `grl` object doesn't have them. What does `seqinfo(grl)` say?

If the chromosome lengths are not there, then you should be able to add them with something like this:
```
seqinfo(grl) <- merge(seqinfo(grl), seqinfo(ref_genome))
seqinfo(grl)
```
Do you see them now?

**Comment by FreekManders** [comment] 2021-02-05 09:14
`plot_rainfall` indeed needs chromosome lengths from the GRanges object. The advice of @hpages should probably work.

@hpages, is it common for BSgenome objects to have a "chromosome_" prefix? The `plot_rainfall` function now removes any "chr" prefix in the labels of the plot with:
`labels <- gsub("chr", "", names(chr_length), ignore.case = TRUE)`
I could add "chromosome_" to this if the prefix is used more often.

**Comment by mullerbsf** [comment] 2021-02-05 15:35
The @hapage solution added correctly the chromosome lengths and the plot_rainfall worked.

@FreekManders, I work with plant genomes. Only for Chlamydomonas reinhardtii that I saw this prefix ("chromosome_"), the majority of other plants are most numeric chromosome ID or with the Chr/chr prefix.

Thank you @hpages and @FreekManders for all your support!

**Comment by hpages** [comment] 2021-02-05 16:32
@FreekManders These are the chromosome names found in the Chlamydomonas reinhardtii assembly provided by JGI. BSgenome objects always use the original chromosome names as-is. They're not in the business of standardizing them.

The prefixes I've seen so far for the chromosome names are: `chr`, `CHR`, `chromosome`, `chromosome_`, `Group`, and I probably forget a few. I don't think it's realistic to aim at automatically removing them programmatically in all situations. Some situations will require user intervention.

@mullerbsf You might consider closing this issue now. If you run into any further problem, please report them in a new issue. Thanks!

**Comment by FreekManders** [comment] 2021-02-06 11:47
@hpages, I understand they can't always be removed. The function removes these prefixes in the labels of the plot to save space and make them less likely to overlap. It is thus mainly an aesthetic convenience for the user. In cases where this doesn't work the user could just change the chromosome names in R or modify the plot in a program like illustrator.

**Closed** 2021-11-24 10:16 UTC
