### ISSUE TITLE
Error in read_vcfs_as_granges

### ISSUE THREAD

**Issue by lincoln-harris** [UMCUGenetics/MutationalPatterns#32] opened 2019-04-26 19:02 UTC
Hi there
I'm running MutationalPatterns on single-cell RNA-seq data, and its working on the majority of my cells. But a few are throwing the following error, from within `read_vcfs_as_granges` i believe:

`Error in .replace_seqlevels_style(x_seqlevels, value) : 
  found no sequence renaming map compatible with seqname style "UCSC" for this object`

what can i do to correct for this? 

(for context im running this on a set of ~10k vcfs, on a very large EC2 instance)

**Comment by FrancisBlokzijl** [comment] 2019-04-29 11:20
Hi Lincoln-Harris,

I suspect there are some chromosome names not compatible with the UCSC naming conventions in your vcf files (some contigs maybe?). Please check that, and if it does not help, please send us a small vcf example file that you cannot load with `read_vcfs_as_granges` then we can see if we can reproduce and fix this problem.

Best,
Francis

**Comment by lincoln-harris** [comment] 2019-04-29 18:37
ok, but the issue is i have no way of knowing which particular vcf file makes it crash out. i give it a list of 10k vcfs, and it works for most but crashes out at some point. is there a way i can modify `read_vcfs_as_granges` to report the name of the file that throws the error?

**Comment by roelj** [comment] 2019-04-30 07:30
Hi Lincoln-Harris,

I created a separate branch for you with the following patch:
https://github.com/UMCUGenetics/MutationalPatterns/commit/2cb879ad3daa02f340d2c18edca5a94761613034

It will display the filename when it crashes.
You should be able to install/use this version by installing it using `devtools`:
```
library(devtools)
devtools::install_github("UMCUGenetics/MutationalPatterns", ref = "lincoln-harris")
```

Could you let me know whether this worked for you?

Kind regards,
Roel

**Comment by lincoln-harris** [comment] 2019-04-30 16:55
thanks a lot! ill try it out.

**Comment by roelj** [comment] 2019-05-09 11:40
Hi @lincoln-harris 

Did you find out what went wrong?  I'd like to see if it's a VCF input error, or whether it's something we could do better in MutationalPatterns.

**Comment by lincoln-harris** [comment] 2019-05-09 16:38
so i realized my vcf files were missing the following header line:

`##fileformat=VCFv4.2`

once i added this, everything got through `read_vcfs_as_granges` without any problems.

**Comment by roelj** [comment] 2019-05-09 19:17
Thanks for your response.  I don't think we can do much about it in MutationalPatterns, because we rely on an external VCF parsing library.

Since the issue is resolved, I'm closing it.

Thanks!

**Closed by roelj** 2019-05-09 19:17 UTC
